KZOO-339-Users_cannot_Join_conference_using_participant_pin
2600hz/kazoo-conference pull request #40
Opened 2022-12-21 03:01 UTC by kdamas93

With this change it is expected to correct the issue that occurs when an offnet call wants to join a conference that does not have an owner, since it is requested a moderator pin and this is not correct.

2022-12-28 18:13 UTC, lazedo requested changes

2022-12-28 18:13 UTC, lazedo commented on src/conf_discovery_req.erl
> +    MemberNumbers = kzd_conferences:member_pins(ConferenceDoc, []),
undo this. what are you trying to do here ?

2022-12-28 18:16 UTC, kdamas93 commented on src/conf_discovery_req.erl
> +    MemberNumbers = kzd_conferences:member_pins(ConferenceDoc, []),
I am taking the pins for the moderator and the participant, I decided to change pins to numbers because numbers is not a value that is filled at any time for the conference, I attach evidence of the investigation:
https://github.com/2600hz/kazoo-conference/pull/39#discussion_r1055603029

2023-01-12 22:55 UTC, jamesaimonetti commented
@kdamas93 i cherry-picked the master PR back as I didn't see any differences.

2023-01-12 22:55 UTC, closed without merging